// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taskato.Data;

namespace Taskato.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Taskato.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Priority 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Priority 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Priority 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Priority 4"
                        });
                });

            modelBuilder.Entity("Taskato.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 5, 10, 10, 50, 39, 325, DateTimeKind.Local).AddTicks(9905),
                            IsCompleted = false,
                            Name = "Learning",
                            PriorityId = 4,
                            TaskDate = new DateTime(2021, 5, 10, 10, 50, 39, 329, DateTimeKind.Local).AddTicks(8383)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 5, 10, 10, 50, 39, 329, DateTimeKind.Local).AddTicks(9213),
                            IsCompleted = false,
                            Name = "Work",
                            PriorityId = 3,
                            TaskDate = new DateTime(2021, 5, 10, 10, 50, 39, 329, DateTimeKind.Local).AddTicks(9227)
                        });
                });

            modelBuilder.Entity("Taskato.Models.Tasks", b =>
                {
                    b.HasOne("Taskato.Models.Priority", "Priority")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("Taskato.Models.Priority", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
